version: '3'
services:

  postgres:
    image: 'postgres:alpine'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
      POSTGRES_DB: keycloak
      POSTGRES_HOST: postgres
    volumes:
      - postgres-vol:/var/lib/postgresql/data

  keycloak:
    image: bitnami/keycloak:12.0.4
    ports:
      - 18443:8443
      - 18080:8080
    depends_on:
      - postgres
    environment:
      KEYCLOAK_DATABASE_HOST: postgres
      KEYCLOAK_DATABASE_PORT: 5432
      KEYCLOAK_DATABASE_NAME: keycloak
      KEYCLOAK_DATABASE_USER: keycloak
      KEYCLOAK_DATABASE_PASSWORD: password
      KEYCLOAK_ADMIN_USER: admin
      KEYCLOAK_ADMIN_PASSWORD: Pa55w0rd
    volumes:
      - ./target/keycloack-listener-0.0.1-SNAPSHOT.jar:/opt/bitnami/keycloak/standalone/deployments/custom-event-listener-0.0.1-SNAPSHOT.jar

volumes:
  postgres-vol:

networks:
  default:
    ipam:
      config:
        - subnet: 10.10.1.0/24